Vagrant.configure("2") do |config|
  config.vm.box = "cloud-image/debian-13"
  # https://portal.cloud.hashicorp.com/vagrant/discover/cloud-image/debian-13
  config.vm.box_version = "20260210.2384.0"

  # Disable synced folder
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # Use cloud-init to execute jobs
  config.vm.cloud_init do |cloud_init|
    cloud_init.content_type = "text/cloud-config"
    cloud_init.inline = <<-EOF
      package_update: true
      packages:
        - nginx
    EOF
  end

  # virtualbox provider
  config.vm.provider :virtualbox do |vb|
    vb.memory = 1024
    vb.cpus = 2
  end
end
