---
ids_interface: "{{ ansible_default_ipv4.interface | default('eth0') }}"
ids_mode: ids # detect-only first
ids_home_net: "10.0.50.0/24"
ids_log_dir: /var/log/suricata
ids_alert_log: fast.log
ids_eve_log: eve.json

ids_rule_path: /var/lib/suricata/rules
ids_rule_files:
  - suricata.rules

ids_update_rules: true
ids_install_evebox: false
ids_suricata_group: suricata
ids_evebox_config_dir: /etc/evebox
ids_evebox_config_path: /etc/evebox/evebox.yaml
ids_evebox_data_dir: /var/lib/evebox
ids_evebox_host: 127.0.0.1
ids_evebox_port: 5636
ids_evebox_auth_required: false
ids_evebox_tls_enabled: false
ids_evebox_retention_days: 7
ids_evebox_input_paths:
  - "{{ ids_log_dir }}/{{ ids_eve_log }}"
