---
- name: Bring up LAN connection
  ansible.builtin.command: nmcli con up "{{ lan_interface }}-lan"
  changed_when: true

- name: Restart dnsmasq
  ansible.builtin.service:
    name: dnsmasq
    state: restarted

- name: Reload nftables
  ansible.builtin.service:
    name: nftables
    state: reloaded
