---
- name: Apply sysctl
  ansible.builtin.command:
    cmd: sysctl -p /etc/sysctl.d/99-openvpn.conf
  changed_when: false

- name: Restart openvpn
  ansible.builtin.systemd:
    name: openvpn-server@{{ openvpn_server_name }}
    state: restarted

- name: Restart openvpn-auth-oauth2
  ansible.builtin.systemd:
    name: openvpn-auth-oauth2
    state: restarted

- name: Apply vpn policy route
  ansible.builtin.shell: |
    ip rule add from {{ openvpn_vpn_subnet }}/24 table 100 2>/dev/null || true
    ip route replace default via 10.0.50.1 table 100
  changed_when: false
