---
- name: Restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted

- name: Restart Apache
  ansible.builtin.service:
    name: apache2
    state: restarted

- name: Restart modsec-json-convert
  ansible.builtin.systemd:
    name: modsec-json-convert
    state: restarted
    daemon_reload: true
