---
- name: Install requirements for alloy
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - wget
      - gnupg
    state: present
    update_cache: true

- name: Ensure APT Keyring directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Download Grafana GPG key
  ansible.builtin.get_url:
    url: https://apt.grafana.com/gpg.key
    dest: /tmp/grafana.gpg.key
    mode: "0644"

- name: Dearmor Grafana GPG key
  ansible.builtin.shell:
    cmd: gpg --dearmor < /tmp/grafana.gpg.key > /etc/apt/keyrings/grafana.gpg
    creates: /etc/apt/keyrings/grafana.gpg

- name: Add Grafana APT repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com stable main"
    filename: grafana
    state: present
    update_cache: true

- name: Install alloy
  ansible.builtin.apt:
    name:
      - alloy
    state: present
    update_cache: true

- name: Add alloy user to log-reading groups
  ansible.builtin.user:
    name: alloy
    groups:
      - adm
      - systemd-journal
    append: true

- name: Deploy Alloy config
  ansible.builtin.template:
    src: alloy-local-config.alloy.j2
    dest: /etc/alloy/config.alloy
    owner: root
    group: alloy
    mode: "0640"
  notify: Restart alloy

- name: Enable and start Alloy service
  ansible.builtin.systemd:
    name: alloy
    enabled: true
    state: started
    daemon_reload: true
